# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookSharing' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BookSharing
pod 'Firebase/Core'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end
